version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  ganache-cli:
    image: 'trufflesuite/ganache-cli:latest'
    container_name: 'ganache-cli'
    ports:
      - '8545:8545'
  p1-bpi:
    build:
      context: ../server
      dockerfile: ../server/Dockerfile
    container_name: 'p1-bpi'
    ports:
      - '3001:3000'
    environment:
      - KAFKA_GROUP='p1-kafka'
    depends_on:
      - kafka
      - ganache-cli
  p2-bpi:
    build:
      context: ../server
      dockerfile: ../server/Dockerfile
    container_name: 'p2-bpi'
    ports:
      - '3002:3000'
    environment:
      - KAFKA_GROUP='p2-kafka'
    depends_on:
      - kafka
      - ganache-cli
